services:
  # the collector receives tracing data from instrumented applications
  # it exports tracing data to jaeger
  # it transforms spans into metric data and exports it to prometheus
  collector:
    # using contrib image to get access to spanmetrics connector
    image: otel/opentelemetry-collector-contrib:0.149.0
    restart: unless-stopped
    volumes:
      - ./config-collector.yaml:/etc/otelcol/config.yaml
    command:
      - "--config=/etc/otelcol/config.yaml"
    ports:
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
    depends_on:
      - jaeger
      - prometheus

  # jaeger is a storage and visualization tool for opentelemetry tracing data
  jaeger:
    image: jaegertracing/jaeger:2.17.0
    restart: unless-stopped
    volumes:
      - ./config-jaeger.yaml:/etc/jaeger/config.yaml
    command: ["--config", "/etc/jaeger/config.yaml"]
    ports:
      - "16686:16686" # jaeger ui
    depends_on:
      - prometheus

  # prometheus is a storage and querying tool for metrics (time series data)
  # jaeger will query prometheus for its monitoring function
  prometheus:
    image: prom/prometheus:v3.11.0
    restart: unless-stopped
    volumes:
      - ./config-prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-tsdb:/prometheus # this is where prometheus stores its time series data
    command:
      # remote write is enabled to use by the collector to push metrics to prometheus,
      # rather than waiting for prometheus to pull the data (reduces memory usage???)
      - "--web.enable-remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090" # prometheus server

volumes:
  prometheus-tsdb:
    name: "prometheus-tsdb"
